### ISSUE TITLE
Ask for Audio Features details

### ISSUE THREAD

**Issue by YangLinyi** [GeminiLn/EarningsCall_Dataset#1]
Hi Yu,

Thanks for sharing the dataset used for your paper. I am wondering the details about the 27 audio features. If it is possible, could you share this part of data with me or could you tell me the full list of these 27 features?

Appreciate for your help! Thanks.

**Comment by GeminiLn** [comment]
Response by Email

**Comment by khanfasheemonowar** [comment]
Hi, can you send me the email too, please ?
