### ISSUE TITLE
How to collect additional data

### ISSUE THREAD

**Issue by d-jiao** [GeminiLn/EarningsCall_Dataset#5]
Hi Yu,

Thanks so much for generously sharing this dataset you collected! I am wondering if you are aware of any alternative data source to collect the earnings call audio data. It seems EarningsCast has no longer been maintained. 

Best, 
Dian

**Comment by GeminiLn** [comment]
Hi Dian,

Thank you for letting me know that EarningsCast is not maintained now. As far as I know, SeekingAlpha is also providing earnings call audio data now. It should be possible to collect both transcripts&audio from SeekingAlpha.

I hope it helps,

Yu
